/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qs_face_QsFace */

#ifndef _Included_com_qs_face_QsFace
#define _Included_com_qs_face_QsFace
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qs_face_QsFace
 * Method:    createEnginge
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_qs_face_QsFace_createEngine
  (JNIEnv *, jobject);

/*
 * Class:     com_qs_face_QsFace
 * Method:    freeEnginge
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_qs_face_QsFace_freeEngine
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_qs_face_QsFace
 * Method:    deteiveFaceFeature
 * Signature: (I[BIIII)[Lcom/qs/face/entity/FaceModel;
 */
JNIEXPORT jobjectArray JNICALL Java_com_qs_face_QsFace_process
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_qs_face_QsFace
 * Method:    compare2Feature
 * Signature: (I[B[B)F
 */
JNIEXPORT jfloat JNICALL Java_com_qs_face_QsFace_compare2Feature
  (JNIEnv *, jobject, jint, jbyteArray, jbyteArray);

/*
 * Class:     com_qs_face_QsFace
 * Method:    compare2Image
 * Signature: (ILjava/lang/String;Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_com_qs_face_QsFace_compare2Image
  (JNIEnv *, jobject, jint, jstring, jstring);

/*
 * Class:     com_qs_face_QsFace
 * Method:    calculateFacePoints
 * Signature: ([BIIIIIII)Lcom/qs/face/entity/FacePointsFeatureResult;
 */
JNIEXPORT jobject JNICALL Java_com_qs_face_QsFace_calculateFacePoints
  (JNIEnv *, jclass, jint ,jbyteArray, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_qs_face_QsFace
 * Method:    antiFakeDetect
 */
JNIEXPORT int JNICALL Java_com_qs_face_QsFace_antiFakeDetect
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jint,jint);

JNIEXPORT jobject JNICALL Java_com_qs_face_QsFace_fatigueDetectAPI
  (JNIEnv *, jobject, jint, jbyteArray, jint, jint, jint);

JNIEXPORT void JNICALL Java_com_qs_face_QsFace_setFatigueDetectCountAPI
  (JNIEnv *, jobject, jint,jint,jint,jint);

#ifdef __cplusplus
}
#endif
#endif
